esphome:
  name: ${dev_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:

api:
  encryption:
    key: ${api_key}

ota:
  - platform: esphome
    password: ${ota_password}

i2c:
  sda: GPIO42
  scl: GPIO41
  id: bus_a
  frequency: 400kHz

uart:
  id: mod_uart
  tx_pin: GPIO17
  rx_pin: GPIO18
  baud_rate: 9600
  stop_bits: 1
  data_bits: 8
  parity: NONE

modbus:
  - uart_id: mod_uart
    id: modbus_server
    send_wait_time: 500ms
    flow_control_pin: 33

modbus_controller:
  - id: r4dcb08_hub
    address: 0x1
    modbus_id: modbus_server
    setup_priority: -10
    update_interval: 5s

pca9554:
  - id: pca9554a_device
    i2c_id: bus_a
    address: 0x20

switch:
  - platform: gpio
    name: "${friendly_name} Relay 1"
    pin: { pca9554: pca9554a_device, number: 0, mode: {output: true} }
  - platform: gpio
    name: "${friendly_name} Relay 2"
    pin: { pca9554: pca9554a_device, number: 1, mode: {output: true} }
  - platform: gpio
    name: "${friendly_name} Relay 3"
    pin: { pca9554: pca9554a_device, number: 2, mode: {output: true} }
  - platform: gpio
    name: "${friendly_name} Relay 4"
    pin: { pca9554: pca9554a_device, number: 3, mode: {output: true} }
  - platform: gpio
    name: "${friendly_name} Relay 5"
    pin: { pca9554: pca9554a_device, number: 4, mode: {output: true} }
  - platform: gpio
    name: "${friendly_name} Relay 6"
    pin: { pca9554: pca9554a_device, number: 5, mode: {output: true} }
  - platform: gpio
    name: "${friendly_name} Relay 7"
    pin: { pca9554: pca9554a_device, number: 6, mode: {output: true} }
  - platform: gpio
    name: "${friendly_name} Relay 8"
    pin: { pca9554: pca9554a_device, number: 7, mode: {output: true} }

sensor:
  - platform: uptime
    id: uptime_sensor

  - platform: modbus_controller
    modbus_controller_id: r4dcb08_hub
    name: "${friendly_name} ${temp1_name}"
    register_type: holding
    address: 0x0
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: r4dcb08_hub
    name: "${friendly_name} ${temp2_name}"
    register_type: holding
    address: 0x1
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: r4dcb08_hub
    name: "${friendly_name} ${temp3_name}"
    register_type: holding
    address: 0x2
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: r4dcb08_hub
    name: "${friendly_name} ${temp4_name}"
    register_type: holding
    address: 0x3
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: r4dcb08_hub
    name: "${friendly_name} ${temp5_name}"
    register_type: holding
    address: 0x5
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: r4dcb08_hub
    name: "${friendly_name} ${temp6_name}"
    register_type: holding
    address: 0x6
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: r4dcb08_hub
    name: "${friendly_name} ${temp7_name}"
    register_type: holding
    address: 0x7
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

globals:
  - id: last_ha_ok
    type: unsigned long
    initial_value: '0'

interval:
  - interval: 1s
    then:
      - if:
          condition: { api.connected: }
          then:
            - lambda: 'id(last_ha_ok) = millis();'
  - interval: 5s
    then:
      - lambda: |-
          if (millis() - id(last_ha_ok) > 30000) {
            ESP_LOGE("watchdog", "HA disconnected >30s, restarting...");
            App.safe_reboot();
          }

# DYNAMICKÝ INCLUDE PODĽA TYPU PRIPOJENIA
<<: !include esp32-s3-eth-8di-8ro-${connection_type}.yaml
