wifi:
  ap:
    ssid: "${dev_name}_Config"
    password: ""

web_server:
  port: 80

ota:
  - platform: esphome

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP"
    mac_address:
      name: "${friendly_name} MAC"
    ssid:
      name: "${friendly_name} Connected SSID"
  - platform: template
    name: "${friendly_name} Uptime"
    lambda: |-
      int seconds = id(uptime_sensor).state;
      int days = seconds / 86400;
      int hours = (seconds % 86400) / 3600;
      int minutes = (seconds % 3600) / 60;
      char buffer[30];
      if (days > 0) sprintf(buffer, "%dd %02dh %02dm", days, hours, minutes);
      else sprintf(buffer, "%02dh %02dm", hours, minutes);
      return std::string(buffer);
    icon: "mdi:clock"
    update_interval: 60s

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
